language: ruby
rvm:
  - 2.1
  - 2.0
branches:
  only:
    - master
before_script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate
script:
  - bundle exec rake spec
notifications:
  email: false
